### ISSUE TITLE
[CRITICAL] Unnecessary code

### ISSUE THREAD

**Issue by ale1313** [gaston-munoz/morty-graphql-react#11]
This comment should not belong to the master branch of an app, neither to a presented product.

https://github.com/gaston-munoz/morty-graphql-react/blob/030bdd14b381549175e1cc93f8ec93beec0dae83/src/components/Modal/CharacterModal.tsx#L67

**Comment by gaston-munoz** [comment]
New commit:

https://github.com/gaston-munoz/morty-graphql-react/commit/aa29c75f64273d42f06591ea7c8bcee040f65f6f
