### ISSUE TITLE
[minor] Usage of render function

### ISSUE THREAD

**Issue by ale1313** [gaston-munoz/morty-graphql-react#12]
Same as #2 , you should use a cleaner render function to handle your conditionally rendered component instead of a messy ternary.

https://github.com/gaston-munoz/morty-graphql-react/blob/030bdd14b381549175e1cc93f8ec93beec0dae83/src/components/Modal/CharacterModal.tsx#L34

**Comment by gaston-munoz** [comment]
Final commit in which I finished solved the issues:
https://github.com/gaston-munoz/morty-graphql-react/commit/514c24afdee385733b64b333637b0f23d0100ea4

**Comment by gaston-munoz** [comment]
New commit:

https://github.com/gaston-munoz/morty-graphql-react/commit/aa29c75f64273d42f06591ea7c8bcee040f65f6f

**Comment by gaston-munoz** [comment]
Solved
