### ISSUE TITLE
[CRITICAL] Reusability and Compartmentalization

### ISSUE THREAD

**Issue by ale1313** [gaston-munoz/morty-graphql-react#13]
According to React's good practices, you should implement a logic of reusability and compartmentalization to your components. As I could see in your modals, you made pretty much the same component with slight differences for each entity, which doesn't corresponds to this React Logic. Please refactor your code so you only use a single component for all your entities and conditionally renders it layout according to each entity design.

**Comment by gaston-munoz** [comment]
Final commit in which I finished solved the issues:
https://github.com/gaston-munoz/morty-graphql-react/commit/514c24afdee385733b64b333637b0f23d0100ea4

**Comment by gaston-munoz** [comment]
New commit:

https://github.com/gaston-munoz/morty-graphql-react/commit/aa29c75f64273d42f06591ea7c8bcee040f65f6f

**Comment by gaston-munoz** [comment]
Solved
