### ISSUE TITLE
[minor] Cross-browser compatibility

### ISSUE THREAD

**Issue by ale1313** [gaston-munoz/morty-graphql-react#15]
As you can see, the `ScrollToOptions` parameter is relatively new and not supported in every browser (and if it's supported it's only on newer versions). You should add a retrocompatible fallback if that's the case for the user. https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo

https://github.com/gaston-munoz/morty-graphql-react/blob/030bdd14b381549175e1cc93f8ec93beec0dae83/src/components/Pagination/index.tsx#L24

**Comment by gaston-munoz** [comment]
Final commit in which I finished solved the issues:
https://github.com/gaston-munoz/morty-graphql-react/commit/514c24afdee385733b64b333637b0f23d0100ea4

**Comment by gaston-munoz** [comment]
New commit:

https://github.com/gaston-munoz/morty-graphql-react/commit/aa29c75f64273d42f06591ea7c8bcee040f65f6f

**Comment by gaston-munoz** [comment]
New commit:

https://github.com/gaston-munoz/morty-graphql-react/commit/aa29c75f64273d42f06591ea7c8bcee040f65f6f
