### ISSUE TITLE
[CRITICAL] Usage of deprecated type

### ISSUE THREAD

**Issue by ale1313** [gaston-munoz/morty-graphql-react#9]
SFC it's a deprecated React Type and should not be used https://stackoverflow.com/questions/53885993/react-16-7-react-sfc-is-now-deprecated

https://github.com/gaston-munoz/morty-graphql-react/blob/030bdd14b381549175e1cc93f8ec93beec0dae83/src/components/Modal/CharacterModal.tsx#L9

**Comment by gaston-munoz** [comment]
New commit:

https://github.com/gaston-munoz/morty-graphql-react/commit/aa29c75f64273d42f06591ea7c8bcee040f65f6f
